# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ff772ac6767319ce473e2adf3377d76bd89e821df24a11e311565638e00adcd7d59b38c62a561f9797fdb1d3894e040e19c9c5f35f46e4fa6ea3ebe87728f9

test:
  secret_key_base: fbdeeaff8340a56a57477e12aa43bb4e92778edff770f27e6a0fd4f2dbeca74abba05668db5514ee37b65d59142f917f5357fcdda04f740695d59030657f7e93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
